### ISSUE TITLE
bugs on fates admin

### ISSUE THREAD

**Issue by TheFateInMe** [fatesc/fates-admin#7]
**Describe the bug**
kill and kill2 fails sometimes, same with the looped versions.
bring and bring2 fails sometimes.
displaynames on doesnt work, and displaynames off fails when you reset or when a new person joins.
savetools fails sometimes.
delete and loopdelete dont work sometimes.

ideas to add:
antikill2
possibly a faster dupe

thats all for now.

**Expected behavior**
i expected most things i said to work but it fails sometimes.

**Screenshots**
cant do screenshots rn

 

```
i dont think it errors it just fails
```

</details>

</details>

**Additional context**

**Comment by Karmasuki** [comment]
nill kiggers

**Comment by NotDSF** [comment]
stfu and grow up

**Comment by Karmasuki** [comment]
cry about it fucking nigger

**Comment by Karmasuki** [comment]
ook ook watermelon ill throw a fucking spear at you and cook you over the fire

**Comment by Karmasuki** [comment]
October 11th, 2026 at 4:23 pm

**Comment by Karmasuki** [comment]
October 11th, 2026 at 4:23 pm

**Comment by Karmasuki** [comment]
October 11th, 2026 at 4:23 pm

**Comment by NotDSF** [comment]
enjoy the github ban :trollface:

**Comment by Karmasuki** [comment]
nope.
