### ISSUE TITLE
Laggy on mm2

### ISSUE THREAD

**Issue by CoolChurro** [fatesc/fates-admin#71]
There's not really much to say, but playing mm2 (murder mystery 2) gets incredibly laggy whenever you use fates admin. It doesn't really happen for any other game except mm2. This happened even before I factory reset my computer. There aren't any errors in the console at all.  I'm using Synapse X.

**Comment by fatesc** [comment]
will look into it

**Comment by fatesc** [comment]
fixed sorry for the long delay, i forgot about this
