### ISSUE TITLE
add a antivoid command

### ISSUE THREAD

**Issue by joshclark756** [fatesc/fates-admin#79]
**Is your feature request related to a problem? Please describe.**
sets fallenpartsdestroyheight to 0/0
**Describe the solution you'd like**
antivoid
**Describe alternatives you've considered**
manually setting it everytime
**Additional context**

**Comment by pozm** [comment]
i would impl in a pull, but currently internet is bricked. have you considered making a plugin which implements this functionality?

**Comment by NotDSF** [comment]
@joshclark756 You might as well make this a plugin because I doubt this will be included however idk

**Comment by joshclark756** [comment]
i put this in autoexec loadstring(game:HttpGet(('https://pastebin.com/raw/PxMdTW15'),true))()

**Comment by pozm** [comment]
???

**Comment by NotDSF** [comment]
fr

**Comment by NotDSF** [comment]
hey pozm when gonna unblock me on discord over a silly copypasta joke??

**Comment by pozm** [comment]
send me your apologies to my email : null@astolfo.uk

**Comment by fatesc** [comment]
will be added for v3
